### ISSUE TITLE
rezervoari

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2014Tim4#17]
U izvještajima spominjete tip (uzemni/nadzemni) i veliki/mali, međutim u FZ za rezerovare se to nigdje ne navodi. Nemate nigdje ni datum baždarenja i period baždarenja, na osnovu kojih možete odrediti kada treba ponovo baždariti.

**Comment by EldarGranulo** [comment]
Na više mjeste izmijenjeno te dodani datum zadnjeg baždarenja, period baždarenja od  6 godina.
