### ISSUE TITLE
3.3.

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2014Tim4#20]
Performanse: 5 sekundi bez ikakvih drugih ograničenja. Znate li šta znači u "realnom vremenu"? "sistem omogućava dovoljan broj zapisa u bazu podataka" ne znači ništa. "Nakon odjave sa posla radnik više ne može pristupati sistemu" portir dođe i ugasi aplikaciju?

**Comment by nurifdedagic** [comment]
Ispravljeno
