### ISSUE TITLE
SQL skripta

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2014Tim4#24]
ERROR 1005 (HY000) at line 13: Can't create table 'tim4.fakture_iznajmljivanje' (errno: 150)

**Comment by EldarGranulo** [comment]
Postavio sam novu skriptu koja je direktno iz MySQL(I prethodna je ali je prerađena).

**Comment by deancupovic** [comment]
Da li je password za mysql usera 2014SIEtf? Tačno ovako, velika mala slova?

**Comment by EldarGranulo** [comment]
Da, username je EtfSI2014, a password 2014SIEtf.

**Comment by deancupovic** [comment]
U stvari vi setujete password u PocetniEkran.java?
I zbog toga vam testovi padaju. Prilikom izvršenja testova nigdje se ne setuje password?

**Comment by EldarGranulo** [comment]
Setujem password tu u preferences za DatabaseUtils klasu koja onda koristi dalje taj password. To je uradjeno da bi se uklonio hard kodirani password zbog Sonar issuesa ali sad vidim da nije riješeno. 
U konstruktoru svake DataSource klase se poziva ta klasa tako da je password setovan

**Comment by deancupovic** [comment]
Jedino mjesto gdje setujete taj password je u PocetniEkran.java?
https://github.com/SoftverInzenjeringETFSA/SI2014Tim4/search?utf8=%E2%9C%93&q=setDBPassword

u DatabaseUtils.java se čita password.

PocetniEkran ce se izvrsiti samo ako pokrenete normalno program i setovace password. Prilikom testiranja PocetniEkran se ne izvršava, samim tim se i password ne setuje?

Da li kod vas prolaze junit testovi?

**Comment by EldarGranulo** [comment]
Sad sam podesio da ako ne daje password tom metodom da mu vrati po defaultu password kroz get metodu pa ga mora imati. Padaju zbog exceptiona, sad ce se ispraviti.

**Comment by EldarGranulo** [comment]
Testovi se ispravljaju pa zatvaram issue.
