### ISSUE TITLE
Prva dva znaka broja lične karte

### ISSUE THREAD

**Issue by ajdinmehic** [SoftverInzenjeringETFSA/SI2014Tim4#25]
Komponenta:
Gassoft desktop

commit ID:
1edeef4bfe

Opis problema:
Prilikom dodavanja komitenta (Fizičko lice) nemoguće je unijeti "00" kao prva dva znaka u polju "Broj lične karte" (iako u upozorenju iskoči "Prva dva znaka moraju biti brojevi"). Također, pogrešno upozorenje se prikaže: "znakovi 4,5,6 moraju biti slova". Ispraviti u "znakovi 3,4,5 moraju biti slova".

http://pokit.org/get/img/aa16f7e0858820134ac30ee53826e9d8.jpg

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Gassoft"
2. U "DodavanjeFizickogKomitenta.java" unijeti "00acb1234" u polje "Broj lične karte"
3. Popuniti ispravno ostala polja
4. Kliknuti na dugme "Dodaj komitenta".

Dobijeni rezultat:
- Na formi se prikaže "Greška kod unosa broja lične karte: Prva dva znaka moraju biti brojevi!"

Očekivani rezultat:
- Očekuje se da nakon klika na "Dodaj komitenta" sva popunjena polja postanu prazna, što znači da je uspješno dodan novi komitent (Fizičko lice).

**Comment by EldarGranulo** [comment]
Ispravljeno.
