### ISSUE TITLE
Odabir tipa korisnika

### ISSUE THREAD

**Issue by ajdinmehic** [SoftverInzenjeringETFSA/SI2014Tim4#26]
Komponenta:
Gassoft desktop

commit ID:
1edeef4bfe

Opis problema:
Prilikom dodavanja korisnika moguće je odabrati oba ponuđena tipa korisnika na dnu forme (Administrator i Korisnik).

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Gassoft"
2. U "DodavanjeNovogKorisnika.java" popuniti ispravno sva polja, a na dnu za tip korisnika označiti i "Administrator" i "Korisnik"
3. Kliknuti na dugme "Dodaj"

http://pokit.org/get/img/9b0364bef7ce8521d31afe08424556d7.jpg

http://pokit.org/get/img/e4758a90d191587c4f32fa15823c426e.jpg

Dobijeni rezultat:
- Sva polja postanu prazna ("Administrator" i "Korisnik" su i dalje označeni), a novi korisnik je dodan

Očekivani rezultat:
- Očekuje se da nakon klika na dugme "Dodaj" iskoči upozorenje kako se mora obilježiti tačno jedan tip korisnika i da do tada uneseni podaci ostanu i dalje na formi

**Comment by EldarGranulo** [comment]
Ispravljeno.
