### ISSUE TITLE
Dodavanje komitenta: nije obavezan unos polja "Ime" i "Prezime"

### ISSUE THREAD

**Issue by ajdinmehic** [SoftverInzenjeringETFSA/SI2014Tim4#27]
Komponenta:
Gassoft desktop

commit ID:
1edeef4bfe

Opis problema:
Iako je u SRS-u naznačeno da sva polja u "Dodavanje komitenta (Fizičko lice)" moraju biti popunjena, prilikom dodavanja komitenta moguće je polja "Ime" i "Prezime" ostaviti prazna, a uspjeti dodati komitenta klikom na dugme "Dodaj komitenta".

![dodavanjekomitenta](https://cloud.githubusercontent.com/assets/11408697/7822644/49c880a4-03f7-11e5-950e-4b8269904778.jpg)

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Gassoft"
2. U "DodavanjeFizickogKomitenta.java" popuniti ispravno sva polja osim "Ime" i "Prezime (njih ostaviti prazna).
3. Kliknuti na dugme "Dodaj komitenta".

Dobijeni rezultat:
- Nakon klika na dugme "Dodaj komitenta" novi je komitent dodan.

Očekivani rezultat:
- Očekuje se da se nakon klika na "Dodaj komitenta" pojavi poruka kako su polja "Ime" i "Prezime" ostala prazna i da se novi komitent ne može dodati dok se i ta polja ne popune.

**Comment by EldarGranulo** [comment]
Ispravljeno.
