### ISSUE TITLE
Dodavanje Novog Korisnika 

### ISSUE THREAD

**Issue by ahasovic1** [SoftverInzenjeringETFSA/SI2014Tim4#38]
Komponenta:
Dodavanje novog korisnika

Opis problema:
Poruka o uspješnom dodavanju korisnika nije implementirana .

Koraci za reproduciranje problema:
Pokrenuti prozor za dodavanje novog korisnika
Unijeti validne podatke
Pritisnuti dugme za dodavanje

Dobijeni rezultat:
Ne ispiše se očekivana poruka o uspješnom dodavanju

Očekivani rezultat: 
Poruka o uspješnom dodavanju

**Comment by EldarGranulo** [comment]
Duplikat issue #32
