### ISSUE TITLE
Nemoguće unijeti tel. broj s pozivnim brojem države (+387 ili 00387...)

### ISSUE THREAD

**Issue by lejlaagic** [SoftverInzenjeringETFSA/SI2014Tim4#42]
Komponenta:
- Dodavanje/izmjena pravnog komitenta / 
- Dodavanje/izmjena fizičkog komitenta / 
- Dodavanje/izmjena korisnika

commit ID:
e5c4028c227447aaa9050684dc91f8a86e4d9fbc

Opis problema: 
- Ukoliko se prilikom dodavanja ili izmjene komitenta ili korisnika unese tel. broj u formatu koji sadrži pozivni broj države, unos neće biti prihvaćen jer telefonski broj može imati 9 ili 10 cifara.

Koraci za reproduciranje sistema :
1. Incijaliziramo bazu s file-om initialize_with_data.sql
2. Buildamo i pokrenemo  aplikaciju
3. Logiramo se s podacima admin, pass
4. Otvorimo tab administracija komitenata
5. Odaberemo dodavanje pravnog komitenta
6. Popunjavamo podacima kao na slici 1 i dodajemo komitenta

Slika 1
![slika1](https://cloud.githubusercontent.com/assets/9222710/7896858/bef472b6-06c7-11e5-8ae6-937ddc9923b2.jpg)

Dobijeni rezultat:
- Forma s porukom o grešci.

Slika 2
![slika2](https://cloud.githubusercontent.com/assets/9222710/7896867/0f1e6f62-06c8-11e5-91df-0c69f18993c5.jpg)

Očekivani rezultat:
- Uspješno dodavanje komitenta.

**Comment by EldarGranulo** [comment]
Smatram da ovo nije greška s obzirom da je u SRS - u naglašeno da je validan broj izdat od BH operatera. Ako je izdat od BH operatera, onda nema potrebe za navođenjem pozivnog broja države.
