### ISSUE TITLE
Dupli unos plinskih rezervoara

### ISSUE THREAD

**Issue by edenasevic** [SoftverInzenjeringETFSA/SI2014Tim4#44]
-Kada se ulogujemo kao administrator i otvorimo tab fakture dobijemo sljedeci izgled: http://prntscr.com/7b2z0m. Odabran je plinski rezervoar sa sifrom 125468. Klikne se na dugme Unesite rezervoare i u tabeli se regularno prikazu podaci o unesenom rezervoaru: http://prntscr.com/7b310g. Ako za isti rezervoar se klikne dugme Unesite rezervoare iskoci message box sa porukom "Vec ste dodali ovaj rezervoar", sto je regularno:  http://prntscr.com/7b31at. 
-Medjutim kada odaberem novi rezervoar tipa "102546" i kliknem na Unesite rezervoare ispise se prethodni rezervoar opet skupa sa novim dodanim rezervoarom u tabeli: http://prntscr.com/7b31z3

Commit id:
e40cb502e67a56895f2570669f012a77888db21f

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju tim4app po uputstvu zadatom u folderu ...\SI2014Tim4\Uputstvo za uspostavljanje radnog okruženja\Uputstvo za uspostavljanje radnog okruženja.pdf.
2. Pokrene se LoginForma.java
3. Pristupni podaci username: admin, sifra: admin
4. Odabere se tab Fakture
5. Odabere se neki rezervoar, klikne se na dugme Unesite Rezervoare,
6. Opet se klikne dugme Unesite Rezervoare za isti rezervoar.
7. Kada iskoci message box klikne se OK.
8. Odabere se drugi rezervoar i klikne se na Unesite Rezervoare. 
9. U tabeli ce se prikazati dva prikaza prvog unesenog rezervoara i jedan prikaz drugog unesenog rezervoara (print screenovi iznad)

Dobijeni rezultat:
-Dva primjera prvog unesenog rezervoara, jedan primjer drugog unesenog rezervoara

Trazeni rezultat:
-Po jedan primjer oba rezervoara 

EDIT:
Greske vrijede i za formu koju dobijemo kada se ulogujemo sa korisnikom

**Comment by EldarGranulo** [comment]
Takođe testiran jedan od ranijih commita, ovaj issue je ispravljen i ranije prijavljen. Commit e5c4028c227447aaa9050684dc91f8a86e4d9fbc.
