### ISSUE TITLE
Radio buttoni na fakture tab-u admin forme

### ISSUE THREAD

**Issue by edenasevic** [SoftverInzenjeringETFSA/SI2014Tim4#45]
Forma za admina, tab fakture. Kada se odabere jedan radio button, drugi se iskljuci na mouse hover, a valjda bi trebalo na mouse click.

Commit Id:
e40cb502e67a56895f2570669f012a77888db21f

Koraci za reproduciranje:
1. Pokrenuti desktop aplikaciju tim4app po uputstvu zadatom u folderu ...\SI2014Tim4\Uputstvo za uspostavljanje radnog okruženja\Uputstvo za uspostavljanje radnog okruženja.pdf.
2. Pokrene se LoginForma.java
3. Pristupni podaci username: admin, sifra: admin
4. Odabere se tab Fakture
5. Klikne se na jedan radio button (Prodaja ili Iznajmljivanje). Predje se misem preko drugog, onaj prvi ce se iskljuciti.

Dobijeni rezultat: 
Iskljucenje na hover

Ocekivani rezultat:
Nista da se ne desi na hover
Greske vrijede i za formu koju dobijemo kada se ulogujemo sa korisnikom

**Comment by EldarGranulo** [comment]
Takođe ispravljeno u commit e5c4028c227447aaa9050684dc91f8a86e4d9fbc, gdje je ovaj issue vec bio linkovan.
