### ISSUE TITLE
Format broja licne karte

### ISSUE THREAD

**Issue by edenasevic** [SoftverInzenjeringETFSA/SI2014Tim4#47]
-Kada pokusavam da registrujem novog korisnika pri unosu se trazi broj licne karte koji ima format (111fff111), tj. 4., 5. i 6. znak moraju biti slova. Međutim i kada unesem slova kao 4. 5. i 6. znak opet mi iskace message box koji prijavljuje gresku da 4. 5. i 6. znakovi moraju biti slova: http://prntscr.com/7b3gkm

Commit ID:
e40cb502e67a56895f2570669f012a77888db21f

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju tim4app po uputstvu zadatom u folderu ...\SI2014Tim4\Uputstvo za uspostavljanje radnog okruženja\Uputstvo za uspostavljanje radnog okruženja.pdf.
2. Pokrene se LoginForma.java
3. Pristupni podaci username: admin, sifra: admin
4. Odabere se tab Administracija Korisnika
5. Klikne se dugme Dodavanje Korisnika
6. Popune se podaci

Dobijeni rezultat:
Greska pri unosu

Ocekivan rezultat:
Ubacivanje novog korisnika u bazu

EDIT:
ista greska se javlja pri dodavanju i izmjene komitmenta kod broja licne karte
Greske vrijede i za formu koju dobijemo kada se ulogujemo sa korisnikom

**Comment by EldarGranulo** [comment]
Format u kojem bi se trebala unijeti lična karta je 11xyz2789 npr., a svi problemi vezano za licnu kartu su ispravljeni u e5c4028c227447aaa9050684dc91f8a86e4d9fbc.
