### ISSUE TITLE
Pozivni brojevi telefona

### ISSUE THREAD

**Issue by edenasevic** [SoftverInzenjeringETFSA/SI2014Tim4#50]
Pri registraciji i izmjeni podataka fizickog komitenta u polje br telefona je moguce unijeti brojeve koji sadrze pozivne brojeve koji nisu iz BiH (066..., 068..., 067..., 069...). Forma: http://prntscr.com/7b3xqw

Commit ID:
e40cb502e67a56895f2570669f012a77888db21f

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju tim4app po uputstvu zadatom u folderu ...\SI2014Tim4\Uputstvo za uspostavljanje radnog okruženja\Uputstvo za uspostavljanje radnog okruženja.pdf.
2. Pokrene se LoginForma.java
3. Pristupni podaci username: admin, sifra: admin
4. Otvori se tab Administracija komitenata, pa na dugme (Dodavanje fizickog komitenta ili Izmjena 
podataka fizickog komitenta)
5. U formi koja se otvori je moguce unijeti gore navedene pozivne brojeve i registrovati/izmijeniti komitent sa tim podacima.

Dobijeni rezultat:
Prosla registracija/izmjena

Ocekivani rezultat:
Neka greska da broj nije iz BiH

EDIT:
Isto vazi i za dodavanje pravnog komitenta
Greske vrijede i za formu koju dobijemo kada se ulogujemo sa korisnikom

**Comment by EldarGranulo** [comment]
Ovdje je takođe testiran stariji commit, ispravljeno u e5c4028c227447aaa9050684dc91f8a86e4d9fbc.
