### ISSUE TITLE
Dodavanje komitenta bez naziva firme

### ISSUE THREAD

**Issue by edenasevic** [SoftverInzenjeringETFSA/SI2014Tim4#51]
Moguce je dodati novi komitent bez unosenja naziva firme. Tim nije moguce ni pretraziti taj komitent jer za pretrazivanje pravnih komitenata nema dovoljno filtera pretrage

Commit ID:
e40cb502e67a56895f2570669f012a77888db21f

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju tim4app po uputstvu zadatom u folderu ...\SI2014Tim4\Uputstvo za uspostavljanje radnog okruženja\Uputstvo za uspostavljanje radnog okruženja.pdf.
2. Pokrene se LoginForma.java
3. Pristupni podaci username: admin, sifra: admin
4. Odabere se tab Administracija Komitenata
5. Klikne se Dodavanje pravnog komitenta
6. Unesu se svi podaci osim naziva firme
7. Klikne se dugme Izmijeni i prodje forma

Dobijeni rezultat:
Forma se submitala bez problema

Ocekivani rezultat:
Trebala bi se javiti neka greska sa povratnom informacijom da se unese i naziv firme

**Comment by EldarGranulo** [comment]
Ovo je ispravljeno u commitu e5c4028c227447aaa9050684dc91f8a86e4d9fbc, tj. testiran je stariji commit.
