### ISSUE TITLE
Ne valja uslov validacije kod broja licne karte

### ISSUE THREAD

**Issue by mnuhodzic** [SoftverInzenjeringETFSA/SI2014Tim4#53]
Greška se javi kada pokusam da dodam novog korisnika,tacnije pri unosu se broja licne karte.
Kada unesem svoj pravi broj licne karte (1T0K00181) iskace mi message box koji kaže da prva dva znaka moraju biti brojevi. Taj uslov ocito nije ispravan jer prva dva znaka ne moraju biti brojevi.
http://prntscr.com/7b8cyz

Commit ID:
e5c4028

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju klikom na Run->”LoginForma” te se ulogovati kao administrator
2. Izabrati tab "Administracija korisnika"
2. Izabrati opciju "Dodavanje korisnika"
3. Unijeti ispravno sva polja.
4. Za broj licne karte unijeti 1T0K00181.

Dobijeni rezultat:
Greska pri unosu broja licne karte

Ocekivan rezultat:
Ubacivanje novog korisnika u bazu

**Comment by mnuhodzic** [comment]
ako postoji duplikat, treba postaviti link na taj issue

**Comment by EldarGranulo** [comment]
Kolegica je ovdje pogriješila.
