### ISSUE TITLE
izmjena podataka kod pravnog komitenta tj. promjena naziva firme

### ISSUE THREAD

**Issue by mnuhodzic** [SoftverInzenjeringETFSA/SI2014Tim4#57]
Greška se javi kada želim da izmijenim naziv firme kod pravnog komitenta.
U tabu Administracija komitenata kliknem na Izmjena podataka pravnog komitenta.
Ispravno unesen naziv firme Kompanija d.d promijenim u ........... i kliknem na "izmijeni" i uspjesno ga izmijenim. 
To ocito nije ispravno jer naziv firme ne moze biti niz tacaka ............
http://prntscr.com/7b9ecs

Commit ID:
e5c4028

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju klikom na Run->”LoginForma” te se ulogovati kao administrator
2. Izabrati tab "Administracija komitenata"
2. Izabrati opciju "Izmjena podataka pravnog komitenta"
3. Odabrati iz liste "Kompanija d.d"
4. Izbrisati postojeci naziv Kompanija d.d i umjesto toga unijeti ............

Dobijeni rezultat:
Uspjesno promijenjeno naziv pravnog komitenta u bazi

Ocekivan rezultat:
Greska pri nesipravnom mijenjanju naziva pravnog komitenta

**Comment by EldarGranulo** [comment]
Smatram da ovo nije bug jer koji je kriterij za validaciju naziva firme? U svakom slučaju nije pokriven SRS - om, a osigurana je bitna validacija za ime. Vlasnik firme sam bira njeno ime i ne može se znati bez tačno utvrđene forme.

**Comment by mnuhodzic** [comment]
Po kojem onda pravilu nije dozvoljen unos ime firme "@@@@" ili "!!!!!!!"? 
Kada se ovo pokusa upisati, pojavljuje se message box "Naziv firme se mora  sastojati samo od razmaka i slova". 
Smatram da je ovo bug i da treba biti ispravljen
