### ISSUE TITLE
greska kod dodavanje plinskih boca(unosu broja boca do 5 litara )

### ISSUE THREAD

**Issue by mnuhodzic** [SoftverInzenjeringETFSA/SI2014Tim4#58]
Greška se javi kada pokusam da dodam plinske boce,tacnije pri unosu broja boca do 5 litara .
Kada unesem broj boca da je 999999999999 ocekujem da iskaci message box koji kaže da kolicina ne moze biti veca od maksimalne, a ustvari se nista ne desi.
To ocito nije ispravno jer 999999999999 je mnogo vise od  maksimalnog broja boca.
http://prntscr.com/7b9ok9

Commit ID:
e5c4028

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju klikom na Run->”LoginForma” te se ulogovati kao administrator
2. Izabrati tab "Administracija rezervoara"
2. Izabrati opciju "Dodavanje plinskih boca"
3. Unijeti ispravno sva polja.
4. Za broj boca do 5 litara unijeti 999999999999.

Dobijeni rezultat:
Nema poruke o ispravnom niti o neispravnom unosu

Ocekivan rezultat:
Izbacivanje poruke da kolicina ne moze biti veca od maksimalne

**Comment by egazetic1** [comment]
http://pokit.org/get/?e684a228c2ec3e642875ff07cdf51216.png 
Poruka postoji o neispravnom unosu kada uradis klik na button "Dodaj boce"

**Comment by mnuhodzic** [comment]
Ne radi se o toj gresci pogrijesila si tab, nije "Fakture" nego "Administracija rezervoara".
I unesi ovo 999999999999

**Comment by EldarGranulo** [comment]
Ovo nije bug, tj. opisano se ne dešava. Poruka se korektno pojavljuje.
