### ISSUE TITLE
Izmjena podataka rezervoara 

### ISSUE THREAD

**Issue by ahasovic1** [SoftverInzenjeringETFSA/SI2014Tim4#59]
Komponenta:
Izmjena podataka rezervoara 

commit ID:
90a5fc1271a9219bb1d0b010abca7d62e7603f1a

Opis problema:
Prolaze random uneseni podaci

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Izabrati opciju izmjene podataka rezervoara
3. Unijeti random validne podatke (ne unešene podatke iz baze)
4. Kliknut dugme "Izmjeni"
5. Paket poslan. Nema upozorenja da se ne radi o podacima iz baze (da nije izabran već postojeći rezervoar).

Dobijeni rezultat:
-Paket poslan na server. Bačen izuzetak. 

Očekivani rezultat:
-Upozorenje da se ne radi o već postojećem rezervoaru.

**Comment by EldarGranulo** [comment]
Mislim da je rok za prijavu istekao, a u pitanju je stariji commit. Bug je ispravljen u nekom od commitova koji su uslijedili.
