### ISSUE TITLE
Izmjena podataka pravnog komitenta

### ISSUE THREAD

**Issue by ahasovic1** [SoftverInzenjeringETFSA/SI2014Tim4#60]
Komponenta:
Prozor "Izmjena podataka pravnog komitenta"

commit ID:
f2a4f74c22b434a7d721629824a2077641858a2e

Opis problema:
Ne može se pokrenuti sam prozor "Izmjena podataka pravnog komitenta"

Koraci za reproduciranje problema:
1. Pokrenuti window "IzmjenaPodatakaPravnogKomitenta"
2. Bacanje izuzetka - prozor nije pokrenut

Dobijeni rezultat:
-Pozor nije pokrenut, bačen izuzetak

Očekivani rezultat:
-Pokrenut window  "IzmjenaPodatakaPravnogKomitenta"

**Comment by EldarGranulo** [comment]
Mislim da je rok za prijavu istekao, a u pitanju je stariji commit. Bug je ispravljen u nekom od commitova koji su uslijedili.
