### ISSUE TITLE
IzmjenaPodatakaKorisnika

### ISSUE THREAD

**Issue by ahasovic1** [SoftverInzenjeringETFSA/SI2014Tim4#61]
Komponenta:
Prozor "IzmjenaPodatakaKorisnika"

commit ID:
4981ac548341dc85974f30ef501b3b7f2594ff2f

Opis problema:
Ne može se pokrenuti sam prozor "IzmjenaPodatakaKorisnika"

Koraci za reproduciranje problema:
1. Pokrenuti window "IzmjenaPodatakaKorisnika"
2. Bacanje izuzetka - prozor nije pokrenut

Dobijeni rezultat:
-Pozor nije pokrenut, bačen izuzetak

Očekivani rezultat:
-Pokrenut window "IzmjenaPodatakaKorisnika"

**Comment by EldarGranulo** [comment]
Mislim da je rok za prijavu istekao, a u pitanju je stariji commit. Bug je ispravljen u nekom od commitova koji su uslijedili.
