### ISSUE TITLE
Dodavanje novog fizičkog komitenta

### ISSUE THREAD

**Issue by ahasovic1** [SoftverInzenjeringETFSA/SI2014Tim4#62]
Komponenta:
Prozor "DodavanjeFizickogKomitenta"

commit ID:
b1b430b4d0c8e7ff7ad426bf9f590df7cf70ae92

Opis problema:
Nema poruke o uspješno dodanom komitentu

Koraci za reproduciranje problema:
1. Pokrenuti window "DodavanjeFizickogKomitenta"
2. Unijeti validne podatke
3. Kliknuti na dugme za unos i spremanje podataka
4. Nema poruke o uspješno dodanom komitentu

Dobijeni rezultat:
-Poruka nije izbačena, podaci unešeni

Očekivani rezultat:
-SRS: "Poruka o uspješnom dodavanju novog fizičkog komitenta ili grešci"

**Comment by EldarGranulo** [comment]
Mislim da je rok za prijavu istekao, a u pitanju je stariji commit. Bug je ispravljen u nekom od commitova koji su uslijedili.
