### ISSUE TITLE
"DodavanjeNovogKorisnika"

### ISSUE THREAD

**Issue by ahasovic1** [SoftverInzenjeringETFSA/SI2014Tim4#63]
Komponenta:
"DodavanjeNovogKorisnika"

commit ID:
4981ac548341dc85974f30ef501b3b7f2594ff2f

Opis problema:
Dodan korisnik sa potojećim korisničkim imenom

Koraci za reproduciranje problema:
1. Pokrenuti window "DodavanjeNovogKorisnika"
2. Unijeti validne podatke
3. Unijeti već postojeće korisničko ime
4. Kliknuti na dugme za unos

Dobijeni rezultat:
-Podaci unešeni

Očekivani rezultat:
-SRS: "Korisničko ime mora biti jedinstveno". Korisničko ime nije validirano, unešen korisnik sa već postojećim korisničkim imenom, očekivano upozorenje na korisničko ime.

**Comment by EldarGranulo** [comment]
Mislim da je rok za prijavu istekao, a u pitanju je stariji commit. Bug je ispravljen u nekom od commitova koji su uslijedili.
